version: '3.2'
services:
    db:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: emu
        volumes:
            - .db-data:/var/lib/postgresql/data
    app:
        build: ./
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/opt/app/backend
        depends_on:
            - db
    frontend:
        image: node:13.13.0-stretch
        volumes:
            - ./emuapp:/opt/app/emuapp
            - ./backend:/opt/app/backend
        working_dir: /opt/app/emuapp
        command: /bin/sh -c "npm install && npm run watch"
volumes:
    .db-data: