FROM python:3.7

COPY ./backend/requirements.txt /opt/app/backend/
RUN pip install psycopg2
RUN pip install -r /opt/app/backend/requirements.txt
COPY ./backend /opt/app/backend

EXPOSE 5000
ENV PYTHONPATH=/opt/app/backend

WORKDIR /opt/app/backend/emuapp
CMD ["gunicorn","-b=127.0.0.1:5000", "wsgi"]

