version: '3.7'
services:
    db:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: emu
        volumes:
            - .db-data:/var/lib/po%stgresql/POSTGRES_DATABASE
    app:
        build: ./
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/opt/app/backend
        depends_on:
            - db
volumes:
    db-data: