"""Added  news

Revision ID: 031a8184cc1e
Revises: c6376bc60080
Create Date: 2020-05-05 16:41:21.574023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031a8184cc1e'
down_revision = 'c6376bc60080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
