"""Adding surveys V6

Revision ID: 1c65959eb0a0
Revises: b08ab86844a6
Create Date: 2020-05-14 18:06:00.806593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c65959eb0a0'
down_revision = 'b08ab86844a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.drop_column('surveys', 'estimated_Time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('estimated_Time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('surveys', 'estimated_time')
    # ### end Alembic commands ###
