"""migration init

Revision ID: 2c77a3acfe25
Revises: eb4f54913271
Create Date: 2020-04-11 13:54:50.939098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c77a3acfe25'
down_revision = 'eb4f54913271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
