"""Survey hotfix

Revision ID: 2fc32f80b449
Revises: 8f730ca13745
Create Date: 2020-05-31 12:19:40.047286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc32f80b449'
down_revision = '8f730ca13745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'questions', ['question_id'], ['id'])
    op.add_column('survey_records', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_records', 'created')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###
