"""Init

Revision ID: 43af377dea2e
Revises: 
Create Date: 2020-05-31 16:19:42.396099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43af377dea2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(), nullable=True),
    sa.Column('sub_part', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('age_group_bottom', sa.Integer(), nullable=True),
    sa.Column('age_group_top', sa.Integer(), nullable=True),
    sa.Column('survey_type', sa.String(), nullable=True),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_has_interests',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('news_id', 'interest_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_has_interests',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'interest_id')
    )
    op.create_table('survey_has_residence_region',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'street_id')
    )
    op.create_table('survey_has_work_region',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'street_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('social_id', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('residence_location_id', sa.Integer(), nullable=True),
    sa.Column('work_location_id', sa.Integer(), nullable=True),
    sa.Column('birthyear', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['residence_location_id'], ['streets.id'], ),
    sa.ForeignKeyConstraint(['work_location_id'], ['streets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_has_interests',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_record_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('user_has_interests')
    op.drop_table('survey_records')
    op.drop_table('question_options')
    op.drop_table('users')
    op.drop_table('survey_has_work_region')
    op.drop_table('survey_has_residence_region')
    op.drop_table('survey_has_interests')
    op.drop_table('questions')
    op.drop_table('news_has_interests')
    op.drop_table('surveys')
    op.drop_table('streets')
    op.drop_table('news')
    op.drop_table('interests')
    # ### end Alembic commands ###
