"""fixing user

Revision ID: 5786f9bdfa30
Revises: 43af377dea2e
Create Date: 2020-05-31 17:57:38.052487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5786f9bdfa30'
down_revision = '43af377dea2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthyear',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'birthyear',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
