"""User-streets relationship

Revision ID: 63b0c3febbd7
Revises: 81526b713db9
Create Date: 2020-05-14 16:23:15.853528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b0c3febbd7'
down_revision = '81526b713db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
