"""Adding surveys V3

Revision ID: 69fd62f9f9c9
Revises: 4cc8fbf182ec
Create Date: 2020-05-14 17:40:11.168524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fd62f9f9c9'
down_revision = '4cc8fbf182ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
