"""Adding description survey

Revision ID: 6ba25e05a1c7
Revises: c9055100dabd
Create Date: 2020-06-03 16:21:43.398625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba25e05a1c7'
down_revision = 'c9055100dabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'description')
    # ### end Alembic commands ###
