"""Changing user schema

Revision ID: 77b9237eb962
Revises: 5d61154315d9
Create Date: 2020-05-14 16:10:44.741529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b9237eb962'
down_revision = '5d61154315d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('residence_location_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('work_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'streets', ['work_location_id'], ['id'])
    op.create_foreign_key(None, 'users', 'streets', ['residence_location_id'], ['id'])
    op.drop_column('users', 'work_location')
    op.drop_column('users', 'residence_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('residence_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('work_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'work_location_id')
    op.drop_column('users', 'residence_location_id')
    # ### end Alembic commands ###
