"""Changes to streets

Revision ID: 81526b713db9
Revises: 77b9237eb962
Create Date: 2020-05-14 16:19:04.288985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81526b713db9'
down_revision = '77b9237eb962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
