"""User residence nullable

Revision ID: 857e2c2647c9
Revises: 93b1d61fbf0d
Create Date: 2020-06-29 18:00:58.391005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857e2c2647c9'
down_revision = '93b1d61fbf0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
