"""Survey hotfix

Revision ID: 8f730ca13745
Revises: e86c2723866c
Create Date: 2020-05-31 11:48:27.821832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f730ca13745'
down_revision = 'e86c2723866c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
