"""Change to streets

Revision ID: 93fd0764a063
Revises: 9b513c833a47
Create Date: 2020-04-27 15:19:25.685417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fd0764a063'
down_revision = '9b513c833a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_parts', sa.Column('part', sa.String(), nullable=True))
    op.add_column('city_parts', sa.Column('street', sa.String(), nullable=True))
    op.add_column('city_parts', sa.Column('sub_part', sa.String(), nullable=True))
    op.drop_column('city_parts', 'cityPart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_parts', sa.Column('cityPart', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('city_parts', 'sub_part')
    op.drop_column('city_parts', 'street')
    op.drop_column('city_parts', 'part')
    # ### end Alembic commands ###
