"""Answer hotfix

Revision ID: 98f93e9bb4ea
Revises: 2fc32f80b449
Create Date: 2020-05-31 12:23:37.659458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f93e9bb4ea'
down_revision = '2fc32f80b449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
