"""Rss address

Revision ID: a8ef2d16d722
Revises: 96693ddf7038
Create Date: 2020-06-08 15:00:49.248638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ef2d16d722'
down_revision = '96693ddf7038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feed_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('rss_feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rss_feed_id'], ['rss_feeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss_feed_address')
    # ### end Alembic commands ###
