"""Adding surveys V4

Revision ID: afcc5b0f366b
Revises: 69fd62f9f9c9
Create Date: 2020-05-14 17:43:03.328026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afcc5b0f366b'
down_revision = '69fd62f9f9c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
