"""Adding surveys V5

Revision ID: b08ab86844a6
Revises: afcc5b0f366b
Create Date: 2020-05-14 17:43:44.011564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08ab86844a6'
down_revision = 'afcc5b0f366b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
