"""Change table name

Revision ID: b097cd5c3bb7
Revises: 93fd0764a063
Create Date: 2020-04-27 15:20:32.101089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b097cd5c3bb7'
down_revision = '93fd0764a063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(), nullable=True),
    sa.Column('sub_part', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('city_parts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_parts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sub_part', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='city_parts_pkey')
    )
    op.drop_table('streets')
    # ### end Alembic commands ###
