"""User-streets relationship fix

Revision ID: bb8b913927b3
Revises: 63b0c3febbd7
Create Date: 2020-05-14 16:25:58.281472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8b913927b3'
down_revision = '63b0c3febbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
