"""Changing user id

Revision ID: c6376bc60080
Revises: eb4f54913271
Create Date: 2020-05-01 17:13:11.589413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6376bc60080'
down_revision = 'eb4f54913271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(), nullable=True),
    sa.Column('sub_part', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_has_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.add_column('users', sa.Column('birthyear', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('residence_location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('work_location', sa.String(), nullable=True))
    op.drop_column('users', 'region')
    op.drop_column('users', 'age_group_id')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('age_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'work_location')
    op.drop_column('users', 'residence_location')
    op.drop_column('users', 'birthyear')
    op.drop_table('user_has_interests')
    op.drop_table('streets')
    # ### end Alembic commands ###
