"""Adding survey note

Revision ID: cd31cd9c3b78
Revises: a8ef2d16d722
Create Date: 2020-06-15 15:15:46.732829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd31cd9c3b78'
down_revision = 'a8ef2d16d722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(32), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_notes')
    # ### end Alembic commands ###
