"""Survey update

Revision ID: e86c2723866c
Revises: 1c65959eb0a0
Create Date: 2020-05-31 11:46:57.920430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86c2723866c'
down_revision = '1c65959eb0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('active_to', sa.DateTime(), nullable=True))
    op.add_column('surveys', sa.Column('survey_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('social_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_id')
    op.drop_column('surveys', 'survey_type')
    op.drop_column('surveys', 'active_to')
    # ### end Alembic commands ###
