export const FETCH_REGINFO_SUCCESS = "FETCH_REGINFO_SUCCESS";
export const FETCH_REGINFO_FAIL = "FETCH_REGINFO_FAIL";
export const POST_REGINFO_SUCCESS = "POST_REGINFO_SUCCESS";
export const POST_REGINFO_FAIL = "POST_REGINFO_FAIL";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_FAIL = "LOADING_FAIL";
export const FETCH_SURVEYSLIST_SUCCESS = "FETCH_SURVEYSLIST_SUCCESS";
export const FETCH_SURVEYSLIST_FAIL = "FETCH_SURVEYSLIST_FAIL";
export const FETCH_SURVEY_SUCCESS = "FETCH_SURVEY_SUCCESS";
export const FETCH_SURVEY_FAIL = "FETCH_SURVEY_FAIL";
export const FETCH_ANSWER_SUCCESS = "FETCH_ANSWER_SUCCESS";
export const FETCH_ANSWER_FAIL = "FETCH_ANSWER_FAIL"

