export const FETCH_REGINFO_SUCCESS = "FETCH_REGINFO_SUCCESS";
export const FETCH_REGINFO_FAIL = "FETCH_REGINFO_FAIL";
export const POST_REGINFO_SUCCESS = "POST_REGINFO_SUCCESS";
export const POST_REGINFO_FAIL = "POST_REGINFO_FAIL";